# Uncomment the next line to define a global platform for your project
# platform :ios, '10.3'

target 'Oviedo Fire iOS Application' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Oviedo Fire iOS Application
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'Oviedo Fire iOS ApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Oviedo Fire iOS ApplicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
